{
 "title": "k6 Load Testing Results By Tags",
 "description": "A dashboard for visualizing results from the k6.io load testing tool by groups, using the InfluxDB exporter.Based on https://grafana.com/dashboards/10660",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "2024-04-11T10:49:48.580Z", "to": "2024-04-11T10:54:46.134Z" },
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting,http_req_failed,checks"
   },
   {
    "name": "URL",
    "label": "URL",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   },
   {
    "name": "Group",
    "label": "Group",
    "query": "SHOW TAG VALUES WITH KEY = \"group\" WHERE $timeFilter"
   },
   {
    "name": "Tag",
    "label": "Tag",
    "query": "SHOW TAG VALUES WITH KEY = \"perfTag\" WHERE $timeFilter"
   },
   {
    "name": "Build",
    "label": "Build",
    "query": "SHOW TAG VALUES WITH KEY = \"pipeline_id\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Req count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Checks count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Req count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "Failed Req count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "PassChecks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value!=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "Response times By perfTag",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "SELECT count(\"value\"), mean(\"value\") as avg, min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 90) as \"p(90)\", percentile(\"value\", 95) as \"p(95)\" FROM \"http_req_duration\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY \"perfTag\""
    }
   ]
  },
  {
   "title": "Passed Checks - perfTag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(none)"
    }
   ]
  },
  {
   "title": "Failed Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 0 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Failed Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 1 AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"vus\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Requests per Second - perfTag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 1 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(none)"
    }
   ]
  },
  {
   "title": "Failed Requests - perfTag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 1 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(none)"
    }
   ]
  },
  {
   "title": "data sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_sent\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "data received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_received\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}