{
 "title": "k6 Load Testing Results By Tags",
 "description": "A dashboard for visualizing results from the k6.io load testing tool by groups, using the InfluxDB exporter.Based on https://grafana.com/dashboards/10660",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "2024-04-11T16:09:18.984Z", "to": "2024-04-11T16:09:45.796Z" },
 "templating": {
  "list": [
   {
    "name": "Build",
    "label": "Build",
    "query": "SHOW TAG VALUES WITH KEY = \"pipeline_id\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Req count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Total Checks count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Successful Req count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND \"error_code\" = '' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Failed Req count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "successful Checks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value!=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "Response times By perfTag",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "SELECT count(\"value\"), mean(\"value\") as avg, min(\"value\"), median(\"value\"), max(\"value\"), percentile(\"value\", 90) as \"p(90)\", percentile(\"value\", 95) as \"p(95)\" FROM \"http_req_duration\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY \"perfTag\""
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "query": "SELECT count(\"value\") as failed_req FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND \"error_code\" != '' AND $timeFilter GROUP BY \"perfTag\""
    }
   ]
  },
  {
   "title": "Passed Checks - perfTag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value=1 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(none)"
    }
   ]
  },
  {
   "title": "Failed Checks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 0 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 1 AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"vus\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Requests - perfTag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 1 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(none)"
    }
   ]
  },
  {
   "title": "Failed Requests - perfTag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"http_req_failed\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND value = 1 AND $timeFilter GROUP BY time($__interval), \"perfTag\" fill(none)"
    }
   ]
  },
  {
   "title": "data sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_sent\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "data received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"data_received\" WHERE (\"pipeline_id\" =~ /^$Build$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}