{
 "title": "k6 Load Testing Results By Groups",
 "description": "A dashboard for visualizing results from the k6.io load testing tool by groups, using the InfluxDB exporter.Based on https://grafana.com/dashboards/10660",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "2023-06-12T10:31:55.065Z", "to": "2023-06-12T10:34:59.063Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting,http_req_failed,checks"
   },
   {
    "name": "URL",
    "label": "URL",
    "query": "SHOW TAG VALUES WITH KEY = \"name\""
   },
   {
    "name": "Group",
    "label": "Group",
    "query": "SHOW TAG VALUES WITH KEY = \"group\" WHERE $timeFilter"
   },
   {
    "name": "Tag",
    "label": "Tag",
    "query": "SHOW TAG VALUES WITH KEY = \"perfTag\" WHERE $timeFilter"
   },
   {
    "name": "Build",
    "label": "Build",
    "query": "SHOW TAG VALUES WITH KEY = \"pipeline_id\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "PassChecks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE value=1 AND $timeFilter"
    }
   ]
  },
  {
   "title": "FailChecks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"checks\" WHERE (\"group\" =~ /^$Group$/) AND $timeFilter GROUP BY time($__interval), \"check\" fill(none)"
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE (\"group\" =~ /^$Group$/ AND \"perfTag\" =~ /^$Tag$/) "
    }
   ]
  },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "URLs and latencies (By Name)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT count(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95), percentile(\"value\", 90) FROM /^$Measurement$/ WHERE (\"group\" =~ /^$Group$/ AND \"perfTag\" =~ /^$Tag$/) AND $timeFilter GROUP BY \"perfTag\""
    }
   ]
  },
  {
   "title": "$Measurement (over time per tag)",
   "type": "timeseries",
   "description": "Grouped by 1 sec intervals and group name",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT median(\"value\") FROM /^$Measurement$/ WHERE (\"name\" =~ /^$URL$/ AND \"group\" =~ /^$Group$/ AND \"perfTag\" =~ /^$Tag$/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)"
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT max(\"value\") FROM /^$Measurement$/ WHERE (\"name\" =~ /^$URL$/ AND \"group\" =~ /^$Group$/ AND \"perfTag\" =~ /^$Tag$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$URL$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$Group$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Tag$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /^$Measurement$/ WHERE (\"name\" =~ /^$URL$/ AND \"group\" =~ /^$Group$/ AND \"perfTag\" =~ /^$Tag$/) AND $timeFilter"
    }
   ]
  }
 ]
}